### ISSUE TITLE
Reload segmentation results of old video

### ISSUE THREAD

**Issue by jkrasnits** [DCS-LCSR/CeleST#10]
Throws error and makes validity bar red.

**Comment by jkrasnits** [comment]
Attempted to access cbl(1,:); index out of bounds because size(cbl)=[0,0].

Error in CSTCheckResults/displayCurrentFrame (line 1168)
        bbox = [ max(1,min(xImage, min(floor(cbl(1,:)-width)-displayAroundWorms))), ... % xMin

Error in CSTCheckResults/selectWorm (line 1757)
            displayCurrentFrame

Error in CSTCheckResults/loadVideoContents (line 1583)
            selectWorm

Error using waitfor
Error while evaluating UIControl Callback

**Comment by ch576** [comment]
Error found to be caused by incomplete write to file saving segmentation data for a particular video. This caused the read to break. Solved by removing deprecated fields
