### ISSUE TITLE
Switch head tail throws error

### ISSUE THREAD

**Issue by jkrasnits** [DCS-LCSR/CeleST#11]
Reference to non-existent field 'skel'.

Error in CSTCheckResults/switchHeadTail (line 317)
            listOfWorms.skel{currentWorm}{ff} =
            listOfWorms.skel{currentWorm}{ff}(:,end:-1:1);

needs dataset verification

**Comment by ch576** [comment]
Corrections to Read and Write Segmentation To TXT caused fields to be properly written to and read from leading to the field being properly filled.
