### ISSUE TITLE
Scaling issues with monitors and resolutions

### ISSUE THREAD

**Issue by jkrasnits** [DCS-LCSR/CeleST#13]
Present in process video and compute measures

Need machine to verify

**Comment by ch576** [comment]
Glare Zones presents similiar issues, specifically being too large to fit the screen on smaller monitors

**Comment by jkrasnits** [comment]
Currently displays and does not throw  an error, but cannot verify if fully working

**Comment by ch576** [comment]
CeleST v2.0-lcsr certified for monitor with screen resolutions of 1600+ x 800+
